# Generated by Django 4.2.4 on 2024-06-28 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duong', '0002_alter_street_category_alter_street_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='street',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='street',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
