# Generated by Django 4.2.4 on 2024-06-29 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duong', '0003_street_latitude_street_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='street',
            name='category2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
